spring:
  application:
    name: chapter-01
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      bootstrap-servers: localhost:10000
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: sample-consumer-group
#      bootstrap-servers: localhost:10000
